### ISSUE TITLE
Add uuid to upload code

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/csbCrawler2Cloud#5]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>a data catalog</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       refer my object by uuid in the object metadata
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>update my data catalog when an event happens to the object (like moving storage tier)</td>
  </tr>
</table>

### Tasks
- [x] Add uuid during file upload process.

**Comment by dneufeldcu** [comment]
See PR: https://github.com/cedardevs/csbCrawler2Cloud/pull/6

**Comment by kenhtanaka** [comment]
Reviewed code and merged pull request
